### ISSUE TITLE
Explicit and Implicit Class Declarations

### ISSUE THREAD

**Issue by nyet07** [gccxml/pygccxml#24]
Hello,

Is there any way to differentiate implicit and explicit constructors, assignment operators and destructors in a c++ class using pygccxml? For example, pygccxml(or gccxml) treats implicit or explicit constructors, destructors or assignment operators as if they are all the same. Even though a class declaration doesn't have any explicit declaration of a constructor(constructor is not explicitly declared either inside public or private field), pygccxml stores those implicit constructors, destructors in its declaration tree, and as far as I know, there is no way to differentiate those that are explicit and those that are not.

Any suggestions would be appreciated.

**Comment by iMichka** [comment]
Hi

basically, if the app that creates the xml files can make the difference, then pygccxml should be able to do (if not we need to add these features). 

gccxml is now deprecated, and is replaced by CastXML, which works with never compilers and uses the clang parser. I am currently working on the usage of CastXML with pygccxml. Around 100 unit tests were failing, and I am down to 35 for the moment. It's a very long and tedious process, especially because I did not write the initial code.

I want first to finish the basic things; all tests need to pass, so that I can push a new pygccxml release. All the work is being done on the develop branch. I don't know if I will have time to test what you ask during the next weeks. You may give it a try with castxml, as the resulting xml files are a little bit different and clang is sometimes better in it's output. Note that castxml is only supported on Mac (and probably linux) for the moment in pygccxml. I did not have time to implement the Windows part.

Ideally it would be great to have a bunch of tests showing what you want to achieve (even if they are failing, it would be just to demonstrate your goal). Then we can work on adding this functionality if it's missing (and if it's possible).

**Comment by zurach** [comment]
Update: 

Under declaration.py file there is "declaration_t" object. It has a property called "is_artificial". It returns a boolean value based on whether a particular declaration is compiler generated or not.

**Comment by iMichka** [comment]
Coming back to this bug 1 year later (you found the solution by yourself, so there was nothing to be done here), but I kept it open because I wanted to dig further. I was not really aware of the is_artificial thing, and it now makes more sens to me as I have been working more regularly on this project.

During the last year I updated the examples infrastructure, so now I was able to add a small example and explanations here:
http://pygccxml.readthedocs.io/en/develop/examples/artificial/example.html

I will close this bug now. Feel free to open a new one if you still encounter problems or have more questions. Thanks.
