### ISSUE TITLE
Parsing C headers comments

### ISSUE THREAD

**Issue by adolia** [gccxml/pygccxml#69]
Hi all!
Is it possible to extract headers comments with structures with pygccxml?
Thanks in advance!

**Comment by iMichka** [comment]
Hi

Not that I am aware of, but if would be a great feature. First it would need to be implemented in CastXML, because pygccxml just reads the xml file produced by CastXML.
Seems there are ways of doing this, for example http://stackoverflow.com/questions/25275212/how-to-extract-comments-and-match-to-declaration-with-recursiveastvisitor-in-lib seems a good starting point.

Once this feature is added to CastXML, I would consider reading the data and add the functionality to pygccxml.

If you just need `annotations`, you can have a look at the annotation mechanism. I have not example for that feature, but there is a test showing how it works: https://github.com/gccxml/pygccxml/blob/475589ce29d0f273d735fc510c7b37cffdd88c8f/unittests/attributes_tester.py

To be clear: it would be possible, but it needs some work and testing. So this will be on my "low-priority" to do list ... but contributions are welcome and I would be willing to help out if there any questions for the implementation.

**Comment by adolia** [comment]
Good, thanks a lot for reply.

**Comment by iMichka** [comment]
I will close this issue as this is not something I plan to work on for the moment. Just so that the issue tracker does not start to get too much cluttered with open issues.
